### ISSUE TITLE
AI Dungeon doesn't use GPT-3 by default

### ISSUE THREAD

**Issue by flarn2006** [elyase/awesome-gpt3#1]
You should probably add a note to AI Dungeon, mentioning how GPT-3 is only used if you have a premium account (or 7-day trial) and select the "Dragon" AI model in the settings.

**Comment by elyase** [comment]
thanks for the clarification. The intention is to showcase products that use GPT-3 in some fashion even if the product is not 100% GPT-3 based (ex: WWO)
